// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxifTUiH4TUNI3gNbuU-ADzVu9RhJkc_0',
    appId: '1:1071143691513:web:133a326334dace10802e28',
    messagingSenderId: '1071143691513',
    projectId: 'usulicius',
    authDomain: 'usulicius.firebaseapp.com',
    storageBucket: 'usulicius.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsrPrmreCUNKTHDSz1ucrQy2oHH1vqRRo',
    appId: '1:1071143691513:android:ce5ce696d88cba87802e28',
    messagingSenderId: '1071143691513',
    projectId: 'usulicius',
    storageBucket: 'usulicius.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaGRXOo9sIR7ScsQ7XWcSAOquuJf6QYbg',
    appId: '1:1071143691513:ios:bfac55144007d162802e28',
    messagingSenderId: '1071143691513',
    projectId: 'usulicius',
    storageBucket: 'usulicius.firebasestorage.app',
    iosBundleId: 'com.example.usuliciusKelompokLucky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaGRXOo9sIR7ScsQ7XWcSAOquuJf6QYbg',
    appId: '1:1071143691513:ios:bfac55144007d162802e28',
    messagingSenderId: '1071143691513',
    projectId: 'usulicius',
    storageBucket: 'usulicius.firebasestorage.app',
    iosBundleId: 'com.example.usuliciusKelompokLucky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxifTUiH4TUNI3gNbuU-ADzVu9RhJkc_0',
    appId: '1:1071143691513:web:af482707902d5fa1802e28',
    messagingSenderId: '1071143691513',
    projectId: 'usulicius',
    authDomain: 'usulicius.firebaseapp.com',
    storageBucket: 'usulicius.firebasestorage.app',
  );
}
